### ISSUE TITLE
beforeHandle is only called after type validation

### ISSUE THREAD

**Issue by deanylev** [elysiajs/elysia#851] opened 2024-09-26 09:03 UTC
### What version of Elysia is running?

1.1.16

### What platform is your computer?

Darwin 24.0.0 arm64 arm

### What steps can reproduce the bug?

1. Set up route with body validation and `beforeHandle`
2. Return something from the `beforeHandle`
3. Make request that fails body validation

Code snippet:
```
import { Elysia, t } from 'elysia';

const app = new Elysia();

app.post('my-route', () => {
    // route logic
  }, {
    beforeHandle: ({ bearer, set }) => {
      console.log('beforeHandle called');
      return 'you shall not pass!';
    },
    body: t.Object({
      myString: t.String(),
    })
  }
);
```

### What is the expected behavior?

The `beforeHandle` is called and validation is not performed as the `beforeHandle` has returned a value

### What do you see instead?

The `beforeHandle` is never called as validation is performed first

### Additional information

This is undesirable because if you are enforcing authentication on an endpoint using the `beforeHandle`, an attacker could still poke at the endpoint and learn the shape of its API without a valid authentication token

**Comment by SaltyAom** [comment] 2024-09-29 10:22
> ### What is the expected behavior?
> The beforeHandle is called and validation is not performed as the beforeHandle has returned a value
>
> ### What do you see instead?
> The beforeHandle is never called as validation is performed first

From the [documentation Essential: Lifecycle](https://elysiajs.com/essential/life-cycle.html)

beforeHandle will **always perform AFTER validation** by design.

We have a **transform** that perform **BEFORE validation**, see

Otherwise, please refers to this image from [Essential: Lifecycle documentation](https://elysiajs.com/essential/life-cycle.html)
![image](https://github.com/user-attachments/assets/55588879-428f-476c-8d42-0abf8d421508)

> ### Additional information
>
> This is undesirable because if you are enforcing authentication on an endpoint using the beforeHandle, an attacker could still poke at the endpoint and learn the shape of its API without a valid authentication token

By default if you set `NODE_ENV` to `production`, type shape of the API for debugging will not be logged.

If you have any questions, feel free to elaborate further.

Closing as completed.

**Closed by SaltyAom** 2024-09-29 10:22 UTC
Labels: bug

**Comment by deanylev** [comment] 2024-09-29 10:41
> By default if you set NODE_ENV to production, type shape of the API for debugging will not be logged.

That's true, but they could still keep making adjusted requests until they stop getting validation errors, albeit that is far harder. Doesn't really seem like transform provides an easy way to avoid that. Not a huge deal though.
