### ISSUE TITLE
Unable to establish WebSocket connection with separated code

### ISSUE THREAD

**Issue by farhantallei** [elysiajs/elysia#326] opened 2023-11-21 15:40 UTC
I am experiencing an issue when trying to separate my WebSocket code into different parts.

The initial code, where everything is in a single block, works fine.
```ts
import { Elysia, t } from "elysia"

const app = new Elysia()
  .group("inbox", (app) =>
    app.ws("join", {
      body: t.Object({
        inboxId: t.String(),
      }),
      message(ws, { inboxId }) {
        ws.send(inboxId)
      },
    })
  )
  .listen(3000)
```

However, when I split the code into separate parts, the WebSocket connection to ws://localhost:3000/inbox/join fails with the error message: `WebSocket connection to 'ws://localhost:3000/inbox/join' failed.`

```ts
const ws = new Elysia().group("inbox", (app) =>
  app.ws("join", {
    body: t.Object({
      inboxId: t.String(),
    }),
    message(ws, { inboxId }) {
      ws.send(inboxId)
    },
  })
)

const app = new Elysia().use(ws).listen(3000)
```

Elysia Version: 0.7.29
Bun Version: 1.0.13

Thank you for your assistance, and I apologize if I am using the framework incorrectly. Your guidance is highly appreciated.

**Comment by WIGGLES-dev** [comment] 2023-12-10 20:56
I ran into this issue too, I think currently websocket connections only work with one segment at the root of your application. This probably needs to go into a feature request (and should really be documented on the website).

**Comment by Mudbill** [comment] 2024-04-07 16:16
I've been encountering this issue as well, and came to report it after testing. It seems like WebSocket connections don't work as intended when behind a `.group` that comes off another instance of `Elysia` than the root instance.

Testing this URI: `ws://localhost:3000/group/ws`

Works:
```typescript
const websocketApp = new Elysia().ws("/ws", {});
const app = new Elysia().group("/group", app => app.use(websocketApp)).listen(3000);
```

Doesn't work:
```typescript
const websocketApp = new Elysia().group("/group", (app) => app.ws("/ws", {}));
const app = new Elysia().use(websocketApp).listen(3000);
```

Notice how the `.group` is simply moved to the other instance.

The server ends up responding with a 400 Bad Request.

**Comment by chefnaphtha** [comment] 2024-06-30 16:14
this still happens, related issue https://github.com/elysiajs/elysia/issues/553

it's really confusing too since the client console just logs this:
![image](https://github.com/elysiajs/elysia/assets/142947721/cf686d86-c7a6-45ad-bedf-145881f8c737)
![image](https://github.com/elysiajs/elysia/assets/142947721/f40d6f0a-d4d9-4cf3-a1b1-aeb60a7968cc)

**Comment by SaltyAom** [comment] 2024-08-30 17:36
This issue have been fixed by previous subsequent patches of Elysia as it's now unable to reproduce the bug in the latest version of Elysia (1.1.9 by the time of writing) with the following code:

```ts
import { Elysia, t } from '../src'

const ws = new Elysia().group('inbox', (app) =>
	app.ws('join', {
		body: t.Object({
			inboxId: t.String()
		}),
		message(ws, { inboxId }) {
			ws.send(inboxId)
		}
	})
)

const app = new Elysia().use(ws).listen(3000)
```

Feel free to reopen the issue if the bug still persist, thanks

**Closed by SaltyAom** 2024-08-30 17:36 UTC
