### ISSUE TITLE
Schema validation incorrect on nested fields?

### ISSUE THREAD

**Issue by m1212e** [elysiajs/elysia#482] opened 2024-02-14 15:34 UTC
### What version of Elysia.JS is running?

0.8.17

### What platform is your computer?

Linux 6.1.0-18-amd64 x86_64 unknown

### What steps can reproduce the bug?

Clone https://github.com/m1212e/elysia-schema-bug and see src/index.ts for the details

### What is the expected behavior?

The schema should be validated correctly

### What do you see instead?

Invalid fields are just passed along

**Comment by mtt-artis** [comment] 2024-02-14 19:03
seems like Pick and Composite don t check additional properties
 
```js
import { TypeCompiler } from '@sinclair/typebox/compiler'
TypeCompiler.Code(
	t.Composite([
		t.Pick(Resource, ["name"]),
		t.Object({
			associatedScopes: t.Optional(t.Array(t.Pick(Scope, ["id"]))),
		})
	])
)
```
```js
return function check(value) {
  return (
    (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
    (typeof value.name === 'string') &&
    (value.associatedScopes !== undefined ? (Array.isArray(value.associatedScopes) && value.associatedScopes.every((value) => ((typeof value === 'object' && value !== null && !Array.isArray(value)) && (typeof value.id === 'string')))) : true)
  )
```

**Comment by m1212e** [comment] 2024-02-18 14:28
Typebox Objects have the `additionalFields` option which specifies this. I'll check if thats what I need.

**Comment by SaltyAom** [comment] 2024-08-30 19:46
Blocking on https://github.com/sinclairzx81/typebox/issues/976

**Comment by SaltyAom** [comment] 2024-09-01 10:20
From https://github.com/sinclairzx81/typebox/issues/976#issuecomment-2322375951

> Hi @SaltyAom ! :)
> 
> 
> 
> So, this issue is partially related to a design aspect of TypeBox. The mapping functions Pick, Omit, Mapped, and Composite will only copy the properties from source types, but not the constraints (such as additionalProperties). The return value from these functions will always be a new TObject type with no constraints (by default). You can think of these functions in a similar way to Type.Object({...}) where constraints (i.e. options) will need to be assigned on type creation.
> 
> 
> 
> There's a couple of reasons why TypeBox doesn't copy over the constraints from the source object; but the main one is to try and ensure the returned JSON schematic is non-closed and ready for additional composition. Note that copying constraints can lead to some problems in some compositions (specifically allOf (Intersect)). There is some high-level info on this at the link below which largely informed the no-copy-constraint design.
> 
> 
> 
> https://json-schema.org/understanding-json-schema/reference/object#extending
> 
> 
> 
> ---
> 
> 
> 
> Here is a fix for the reproduction code. The update was just to ensure the `AssociatedScope` had an additionalProperties constraint applied to it on Pick, the other was to apply additionalProperties to the Composite options (and not the interior Object)
> 
> 
> 
> ```typescript
> 
> import { Type } from '@sinclair/typebox'
> 
> import { Value } from '@sinclair/typebox/value'
> 
> 
> 
> const Resource = Type.Object({
> 
>   name: Type.String()
> 
> })
> 
> 
> 
> const Scope = Type.Object({
> 
>   id: Type.String()
> 
> })
> 
> 
> 
> // Object mapping types such as Pick, Omit and Mapped will only copy properties from the 
> 
> // source object, but do not copy constraints (such as additionalProperties). The type 
> 
> // returned from these functions will always be a new TObject. They can be thought of
> 
> // as aliases for Type.Object({...}) where constaints are applied via options on the
> 
> // last argument. 
> 
> const AssociatedScope = Type.Pick(Scope, ['id'], {
> 
>   additionalProperties: false
> 
> })
> 
> 
> 
> // Composite works similar to Pick, Omit and Mapped in that it doesn't copy the
> 
> // constaints from the source objects. This type can also be thought of as an
> 
> // Type.Object({...}) where constaints are applied via options.
> 
> const model = Type.Composite([
> 
>   Type.Pick(Resource, ['name']),
> 
>   Type.Object({
> 
>     associatedScopes: Type.Optional(Type.Array(AssociatedScope))
> 
>   })
> 
> ], {
> 
>   additionalProperties: false
> 
> })
> 
> 
> 
> 
> 
> const value = {
> 
>   name: 'string',
> 
>   associatedScopes: [
> 
>     {
> 
>       id: 'a9f10990-2593-45cf-9876-95d75649afc6',
> 
>       blahhh: 'adawdwad' // Should be invalid
> 
>     }
> 
>   ]
> 
> }
> 
> 
> 
> console.log(Value.Check(model, value))  // false
> 
> ```
> 
> Hope this helps
> 
> S

Closing as this is intentional by design. Thanks.

**Closed** 2024-09-01 10:21 UTC
Labels: bug, blocking
