### ISSUE TITLE
Global Schema does not work

### ISSUE THREAD

**Issue by youcefs21** [elysiajs/elysia#388] opened 2023-12-30 23:08 UTC
The code example as given in the [docs](https://elysiajs.com/essential/schema#global-schema) does not work

```ts
import { Elysia, t} from 'elysia'

new Elysia()
    .get('/none', () => 'hi')
    .schema({ 
        query: t.Object({ 
            name: t.String() 
        }) 
    }) 
    .get('/query', ({ query: { name } }) => name)
    .listen(3000)
```

I'm getting a "This expression is not callable." error on `schema`. Looking at the types, schema is of type `Routes` for some reason, which doesn't sound right.

This is not just incorrect typing, putting the code in a js file and trying to run it anyway gives a "schema is not a function." error message

**Comment by tjapa** [comment] 2023-12-31 01:58
same here

**Comment by erhant** [comment] 2024-01-19 21:38
also having this issue

**Comment by cybercoder-naj** [comment] 2024-03-09 00:21
I am having the same issue. Is this being looked at?

**Comment by SaltyAom** [comment] 2024-08-30 18:13
Should have been fixed in the previous subsequent versions of Elysia as unable to reproduce in the latest version (1.1.9) with the following code:
```ts
import { Elysia, t } from '../src'

const app = new Elysia()
	.get('/none', () => 'hi')
	.guard({
		query: t.Object({
			name: t.String()
		})
	})
	.get('/query', ({ query: { name } }) => name)
	.get('/any', ({ query }) => query)

app.handle(new Request('http://localhost:3000/query'))
	.then((x) => x.text())
	.then(console.log)

app.handle(new Request('http://localhost:3000/query?name=hi'))
	.then((x) => x.text())
	.then(console.log)
```

If this doesn't fix your problem, feel free to reopen the issue.

**Closed by SaltyAom** 2024-08-30 18:13 UTC
