### ISSUE TITLE
Types for JWT plugin are not propagated correctly

### ISSUE THREAD

**Issue by l2ysho** [elysiajs/elysia#224] opened 2023-09-24 17:24 UTC
It seems my `jwtFunc` is correctly propagated only to directly chained request handlers, not to plugins or functional callbacks. Is this issue or there is another way how to have correct typing if handlers are in separe files?

```javascript
const JWTMiddleware = jwt({
  name: 'jwtFunc',
  secret: 'password',
})

/*
* Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
* string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
* Request; store: {}; }'.
*/

const plugin = new Elysia().get('/sign/:name', ({ jwtFunc, params }) =>
  jwtFunc.sign(params)
)

/*
* Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
* string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
* Request; store: {}; }'.
*/

export const functionalCallback = (app: Elysia) =>
  app.get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params))

const app = new Elysia()
  .use(JWTMiddleware)
  .use(cookie())
  .use(swagger())
  .use(plugin)
  .use(functionalCallback)
  .get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params)) // this is OK
  ```

**Comment by sagnax** [comment] 2023-09-25 03:53
I'm also getting the same error

**Comment by kingstonbg** [comment] 2023-09-28 08:20
I got the same issue.

**Comment by adicco** [comment] 2023-09-28 16:55
Same issue here, the [example](https://github.com/elysiajs/elysia-jwt/blob/main/example/index.ts) actually raises a TS error on 'jwt' at `.get('/sign/:name', async ({ jwt, cookie, setCookie, params }) =>`

**Comment by hamidabdulmalik** [comment] 2023-10-01 00:56
any updates on this yet guys?

**Comment by sokhengpory** [comment] 2023-10-08 12:07
I think this might be what you're looking for [Dependency Injection](https://elysiajs.com/patterns/dependency-injection.html)

**Comment by lvlingxiao1** [comment] 2023-10-15 20:34
A temporary fix is to downgrade Elysia to 0.7.15, seems it got broken in 0.7.16

**Comment by mateusavila** [comment] 2023-10-26 02:11
Same as well with me. Help Salty!!!

**Comment by silicakes** [comment] 2023-11-11 15:59
It happens to me too but I get why its hard to infer:

You create detached middlewares/plugins/derivations(decide on the name already lol) but the plugin itself is registered on some root app instance.

So the root app is quite aware of the plugins it passes to its context, however, the standalone functions aren't because there's no guarantee for them to be executed in this context, or at least - there's no way to type this kind of guaranty AFAIK.

**Comment by Kazuma-Sadakane** [comment] 2023-12-24 05:02
update elysia ^0.7.0 -> ^0.8.0.

**Comment by kravetsone** [comment] 2024-03-18 16:27
> It seems my `jwtFunc` is correctly propagated only to directly chained request handlers, not to plugins or functional callbacks. Is this issue or there is another way how to have correct typing if handlers are in separe files?
> 
> ```js
> const JWTMiddleware = jwt({
>   name: 'jwtFunc',
>   secret: 'password',
> })
> 
> /*
> * Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
> * string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
> * Request; store: {}; }'.
> */
> 
> const plugin = new Elysia().get('/sign/:name', ({ jwtFunc, params }) =>
>   jwtFunc.sign(params)
> )
> 
> /*
> * Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
> * string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
> * Request; store: {}; }'.
> */
> 
> export const functionalCallback = (app: Elysia) =>
>   app.get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params))
> 
> const app = new Elysia()
>   .use(JWTMiddleware)
>   .use(cookie())
>   .use(swagger())
>   .use(plugin)
>   .use(functionalCallback)
>   .get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params)) // this is OK
> ```

See example in [Documentation - Plugin#service-locator](https://elysiajs.com/essential/plugin.html#service-locator)

**Comment by SaltyAom** [comment] 2024-08-30 11:15
> > It seems my `jwtFunc` is correctly propagated only to directly chained request handlers, not to plugins or functional callbacks. Is this issue or there is another way how to have correct typing if handlers are in separe files?
> > ```js
> > const JWTMiddleware = jwt({
> >   name: 'jwtFunc',
> >   secret: 'password',
> > })
> > 
> > /*
> > * Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
> > * string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
> > * Request; store: {}; }'.
> > */
> > 
> > const plugin = new Elysia().get('/sign/:name', ({ jwtFunc, params }) =>
> >   jwtFunc.sign(params)
> > )
> > 
> > /*
> > * Property 'jwtFunc' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: Record<"name",
> > * string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request:
> > * Request; store: {}; }'.
> > */
> > 
> > export const functionalCallback = (app: Elysia) =>
> >   app.get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params))
> > 
> > const app = new Elysia()
> >   .use(JWTMiddleware)
> >   .use(cookie())
> >   .use(swagger())
> >   .use(plugin)
> >   .use(functionalCallback)
> >   .get('/sign/:name', ({ jwtFunc, params }) => jwtFunc.sign(params)) // this is OK
> > ```
> 
> See example in [Documentation - Plugin#service-locator](https://elysiajs.com/essential/plugin.html#service-locator)

Close as unable to reproduce on my end, either it was fixed in previous subsequent version and service locator pattern.

Feels free to open a new issue referencing this one if the problem still persists.

**Closed by SaltyAom** 2024-08-30 11:15 UTC
