### ISSUE TITLE
set.status isn't working

### ISSUE THREAD

**Issue by mvolkmann** [elysiajs/elysia#415] opened 2024-01-12 17:01 UTC
I have this endpoint definition that sets `set.status` to 400 and logs that it does so.
But the actual response status I see in Chrome DevTools is always 200.
Am I doing something wrong?

```ts
app.post('/account', ({body, set}: any) => {
  const {email, password} = body;
  const goodEmail = validEmail(email);
  const goodPassword = validPassword(password);
  const good = goodEmail && goodPassword;
  set.status = good ? 200 : 400;
  console.log('/account: set.status =', set.status);
  return <span>{good ? 'A new account was created.' : ''}</span>;
});
```

**Comment by mvolkmann** [comment] 2024-01-12 18:26
In my case the request is coming from the browser using htmx. Htmx takes that HTML response and inserts it into the DOM. It doesn't seem though that htmx has any impact on this because I see in the DevTools Network tab that a POST request is sent and the response status is 200 even though I log on the server that it is 400.

**Comment by mvolkmann** [comment] 2024-01-12 18:35
I just tried changing my endpoint to return a string instead of HTML.
That fixes the problem with the response status code.
So something about returning HTML using JSX seems to break the functionality of `set.status`.

**Comment by eduwr** [comment] 2024-01-17 04:04
@mvolkmann it looks like a bug on elysia-html package

I found a similar issue on their repository you can check there
https://github.com/elysiajs/elysia-html/issues/56

**Comment by Coachonko** [comment] 2024-04-10 21:15
Oh I am experiencing the same issue. Is there a workaround?

**Comment by SaltyAom** [comment] 2024-08-30 18:17
Unable to reproduce in the latest Elysia version, closing as complete.

If the problem still persists, feel free to reopen the issue. Thanks.

**Closed by SaltyAom** 2024-08-30 18:17 UTC
