### ISSUE TITLE
Typescript warnings when defining params and using context

### ISSUE THREAD

**Issue by dezoito** [elysiajs/elysia#234] opened 2023-09-27 20:38 UTC
Hello, 

Looks like one of the recent releases brought issues when using params in the route that are passed to a handler function:

![image](https://github.com/elysiajs/elysia/assets/6494010/3a8e927f-953f-4a39-ae4f-1aef4571888f)

Taking a closer look at what typescript is complaining about:

```
Argument of type '{ body: unknown; query: Record<string, string | null>; params: Record<"base" | "term", string>; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request: Request; store: {}; }' is not assignable to parameter of type '{ body: unknown; query: Record<string, string | null>; params: never; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request: Request; store: {}; }'.
  Types of property 'params' are incompatible.
    **Type 'Record<"base" | "term", string>' is not assignable to type 'never'.ts(2345)**
```

Basically, the type for the params defined for that route (`Record<"base" | "term", string>`) are not compatible to `never`, which is the type defined in `Context`.

@SaltyAom , curiously, if I remove the params from the route, the TS error disappears:

![image](https://github.com/elysiajs/elysia/assets/6494010/f5ad3629-5a17-4974-8636-7d5fd65ba401)

Dep versions:
 + bun-types@1.0.3
 + @elysiajs/cors@0.6.0
 + @elysiajs/swagger@0.6.2
 + elysia@0.7.14

The `getSearch` handler function is defined as:

```ts
export const getSearch = async (context: Context) => {
  console.log(context.query);
  console.log(context.params);

  return "Search handler returned";
};
```
Thank you!

**Comment by cheersmas** [comment] 2023-09-28 04:21
Have something similar.
Same case, I've contracted out the handler but the return type and arguments types aren't working if I assign them Handler or Context. 

The context becomes incompatible if I specify the type with parameters or try to de-structure the context to get params or body.

<img width="811" alt="image" src="https://github.com/elysiajs/elysia/assets/41203791/20e0e989-345c-4006-a037-bfed9abacf99">

**Comment by dezoito** [comment] 2023-09-28 11:33
> I've contracted out the handler

That does look cleaner ;)

**Comment by dbarkowsky** [comment] 2023-11-05 18:49
This continues to be an issue. I've tried separating the handler from the route and keeping it included, as seen here:
<img width="1009" alt="image" src="https://github.com/elysiajs/elysia/assets/37922247/bee47bc7-2e03-4482-96eb-1effe5ca6813">

This is a major blocker to using Elysia at the moment.

**Comment by SaltyAom** [comment] 2024-08-30 11:18
Closing as unable to reproduce in previous subsequent version of Elysia.
Either this was fixed or I'm unable to reproduce on my end.

As for passing context, it's recommended to handle Context type as document in [MVC pattern](https://elysiajs.com/patterns/mvc.html#mvc-pattern)

**Closed by SaltyAom** 2024-08-30 11:18 UTC
