### ISSUE TITLE
Accessing all query params using property name (`ctx.query`) doesn't work anymore

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#548] opened 2024-03-18 00:01 UTC
### What version of Elysia.JS is running?

1.0.0

### What steps can reproduce the bug?

Test file:

```ts
// query.ts
import { Elysia } from './src'

import { describe, expect, it } from 'bun:test'

describe('Query', () => {
	it('access all using property name', async () => {
		const app = new Elysia().get('/', (ctx) => ctx.query)
		const response = await app.handle(req())

		expect(await response.json()).toEqual({ name: 'sucrose' })
	})

	it('access all using destructuring', async () => {
		const app = new Elysia().get('/', ({ query }) => query)
		const response = await app.handle(req())

		expect(await response.json()).toEqual({ name: 'sucrose' })
	})

	it('access single param using property name', async () => {
		const app = new Elysia().get('/', (ctx) => ctx.query.name)
		const response = await app.handle(req())

		expect(await response.text()).toEqual('sucrose')
	})

	it('access single param using destructuring', async () => {
		const app = new Elysia().get('/', ({ query: { name } }) => name)
		const response = await app.handle(req())

		expect(await response.text()).toEqual('sucrose')
	})
})

const req = () => new Request(`http://localhost/?name=sucrose`)
```

Run:

```bash
bun test ./query.ts
```

### What is the expected behavior?

all tests pass

### What do you see instead?

first test fails: `Query > access all using property name`:

```diff
error: expect(received).toEqual(expected)

+ {}
- {
-   name: "sucrose",
- }

- Expected  - 3
+ Received  + 1
```

### Additional information

this used to work back in version `0.8.8`

**Comment by SaltyAom** [comment] 2024-03-18 07:03
Ops, seems like referencing the issue id on commit closes the issue automatically. <img src=https://github.com/elysiajs/elysia/assets/35027979/2905e8bc-315b-47b2-836e-81e862761243 alt='Arona confused' width=32 />

Anyway, should be fixed in 1.0.1, also added test cases, thanks!

**Comment by bogeychan** [comment] 2024-03-18 14:06
yay, just updated to `1.0.3` and it works 🎉

---

_BUT_ i found one more case where it doesn't work 😭

```ts
it('access all using destructuring assignment', async () => {
	const app = new Elysia().get('/', (ctx) => {
		const { query } = ctx
		return query
	})
	const response = await app.handle(req())

	expect(await response.json()).toEqual({ name: 'sucrose' })
})

it('access all using destructuring assignment within derive', async () => {
	const app = new Elysia()
		.derive((ctx) => {
			const { query } = ctx
			return {
				yay() {
					return query
				}
			}
		})
		.get('/', (ctx) => ctx.yay())
	const response = await app.handle(req())

	expect(await response.json()).toEqual({ name: 'sucrose' })
})

it('access all using property name within derive', async () => {
	const app = new Elysia()
		.derive((ctx) => {
			return {
				yay() {
					return ctx.query
				}
			}
		})
		.get('/', (ctx) => ctx.yay())
	const response = await app.handle(req())

	expect(await response.json()).toEqual({ name: 'sucrose' })
})
```

The second test fails too: `Query > access all using destructuring assignment within derive`

**Comment by SaltyAom** [comment] 2024-08-30 20:18
This should have been fixed by the latest version as removable of static query analysis on Sucrose.

Also unable to reproduce on 1.1 as well, closing.
If the problem still persist feels free to reopen the issue.

**Closed by SaltyAom** 2024-08-30 20:18 UTC
Labels: bug
