### ISSUE TITLE
Cannot access derive properties in macro

### ISSUE THREAD

**Issue by raggesilver** [elysiajs/elysia#558] opened 2024-03-19 14:47 UTC
### What version of Elysia.JS is running?

1.0.5

### What platform is your computer?

Darwin 23.2.0 x86_64 i386

### What steps can reproduce the bug?

```ts
export const example = new Elysia()
  .derive({ as: "scoped" }, async () => {
    return { myProp: 42 };
  })
  .macro(({ onBeforeHandle }) => ({
    public: (_?: boolean) => {
      onBeforeHandle(ctx => {
        ctx.myProp; // myProp is number | undefined, but it is always undefined in runtime
      });
    },
  }));
```

### What is the expected behavior?

We should be able to access derived props in the same scope.

### What do you see instead?

Props are typed as maybe undefined and are all undefined during runtime.

**Comment by SaltyAom** [comment] 2024-06-06 05:18
Hi, this is an expected behavior

This happens because of the scoping mechanism.
`macro` is global and applies to all routes while `derive` is defined for a subset of routes.

This means `derive` properties apply to self and parent, but not a scope beyond that in contrast to a global macro.
On the scope beyond the parent scope, `myProp` will be undefined while in self and parent is not.

Macro is public and can apply to any route so macro has to consider both scenarios, both `myProp` with value (in scope) and not (goes beyond scope).

Consider this code:
```ts
const plugin = new Elysia()
	.derive({ as: 'scoped' }, () => {
		return { myProp: 42 }
	})
	.macro(({ onBeforeHandle }) => ({
		public(_?: boolean) {
			onBeforeHandle(({ myProp }) => {
				console.log(myProp)
			})
		}
	}))
	.get('/', 'hi', {
		'public': true
	})

plugin.handle(new Request("http://localhost"))
```

In this code, `myProp` will be `42` because derive is applied to self which includes `/`.

However, in this code:
```ts
import { Elysia } from '../src'

const plugin = new Elysia()
	.derive({ as: 'scoped' }, () => {
		return { myProp: 42 }
	})
	.macro(({ onBeforeHandle }) => ({
		public(_?: boolean) {
			onBeforeHandle(({ myProp }) => {
				console.log(myProp)
			})
		}
	}))

const parent = new Elysia().use(plugin)

const main = new Elysia().use(parent).get('/', 'hi', {
	public: true
})

main.handle(new Request('http://localhost'))
```

In this code, `myProp` will be `undefined` because it goes out of (parent) scope.

However, if you set `derive` scope to `global`, `myProp` would not be `undefined` because `derive` is applied globally on the same scope as `macro`.

Setting `derive` as `scoped`:
<img width="1920" alt="Screenshot 2567-06-06 at 12 14 13" src="https://github.com/elysiajs/elysia/assets/35027979/d13fd8f5-5261-4dd4-a933-ecc2f7649e4e">

Setting `derive` as `global`:
<img width="1920" alt="Screenshot 2567-06-06 at 12 14 20" src="https://github.com/elysiajs/elysia/assets/35027979/1f4bb3a3-ad12-40dc-b1a0-2f6266d1b5af">

So the current behavior is correct because `myProp` could be either `42` or `undefined` because `derive` is defined as `scope` or `local`.

I'm closing the issue because this is not a bug but **an intended feature to help developers catch bugs** but feels free to continue the discussion if something is not clear or if you have more questions.

Thank you.

**Closed by SaltyAom** 2024-06-06 05:18 UTC
Labels: bug, good first issue

**Comment by ZeroAurora** [comment] 2025-03-01 14:25
@SaltyAom I came across this problem today. Specifically, I wanted to derive the bearer key from header, then validate the key in a marco. Can we have this behavior documented? Or do we have a cleaner way to do that as a whole in one marco?
