### ISSUE TITLE
Async in plugins within a guard will fail

### ISSUE THREAD

**Issue by KaruroChori** [elysiajs/elysia#481] opened 2024-02-13 18:51 UTC
### What version of Elysia.JS is running?

0.8.15

### What platform is your computer?

Linux 6.5.0-5-generic x86_64 x86_64

### What steps can reproduce the bug?

Plugins using await in the returned `plugin` function will fail when used inside a guard, but not outside it.
For example 
```
function test() {
  const tmp = new Elysia({
    prefix: "",
    name: "test",
    seed: 100,
  });

  function compute() {
    tmp.get("banana", () => "magika");
  }

  return async function plugin(app: Elysia) {
    await compute();
    app.use(tmp);

    return app;
  };
}
```
When used as a plugin will fail inside a guard, but succeed outside. Removing await from compute means it works again in both scenarios.

### What is the expected behavior?

Plugins should be usable also within a guard.

### What do you see instead?

Plugins are not usable within a guard. Specifically routes will not be appended.

### Additional information

This is affecting multiple community plugins, for example `autoroutes`.

**Comment by PandaWorker** [comment] 2024-02-18 14:43
Maybe we should add returning an elysia instance?

```ts
import { Elysia, t } from 'elysia';

function createRouter() {
	const router = new Elysia({
		prefix: '',
		name: 'test',
		seed: 100,
	});

	function search() {
		return router.get('/', () => []);
	}

	function getById() {
		return router.get('/:id', () => {});
	}

	function create() {
		return router.post('/:id', () => {});
	}

	function remove() {
		return router.delete('/:id', () => {});
	}

	return async function plugin(app: Elysia) {
		const composition = router
			.use(search)
			.use(getById)
			.use(create)
			.use(remove);

		return app.use(composition);
	};
}

const app = new Elysia().use(createRouter());
```

**Comment by SaltyAom** [comment] 2024-08-30 19:11
Should have been fixed by previous subsequent Elysia version/patches as unable to reproduce in the latest version of Elysia (1.1.9)

```ts
import { Elysia } from 'elysia'

function test() {
	const tmp = new Elysia({
		prefix: '',
		name: 'test',
		seed: 100
	})

	function compute() {
		tmp.get('banana', () => 'magika')
	}

	return async function plugin(app: Elysia) {
		await compute()
		app.use(tmp)

		return app
	}
}

const app = new Elysia().use(test())

await app.modules

app.handle(new Request('http://localhost/banana'))
	.then((res) => res.text())
	.then(console.log)
```

If the problem still persists, feel free to reopen the issue. Thanks.

**Closed by SaltyAom** 2024-08-30 19:11 UTC
Labels: bug
