### ISSUE TITLE
Routes from app with `scoped: true` are not accessible

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#397] opened 2024-01-05 13:35 UTC
Consider this example:
```tsx
const router = new Elysia({ scoped: true })
  .use(someMiddleware)
  .get("/scoped", () => "ok");

const app = new Elysia().use(router);

const response = await app.handle(new Request("http://localhost/scoped"));

// response.status is 404, expected is 200
```

The routes from scoped instance should still be exposed, right?

**Comment by amritk** [comment] 2024-01-28 01:22
Having the same issue, soon as you add scoped, the routes return not found

**Comment by hansaskov** [comment] 2024-01-31 15:15
I have the same bug. Anyone found a fix?

**Comment by SaltyAom** [comment] 2024-08-30 18:33
Unable to reproduce with the following code on the latest version (1.1.9)
```ts
const router = new Elysia({ scoped: true }).get('/scoped', () => 'ok')

const app = new Elysia().use(router)

const response = await app.handle(new Request('http://localhost/scoped'))

console.log(response.status) // 200
```

Probably have been fixed with the previous subsequent version. Feel free to reopen the issue if problem still persist.

**Closed by SaltyAom** 2024-08-30 18:33 UTC
