### ISSUE TITLE
migrating from 0.8.1 -> 1.0.0 causing "error: Duplicate type kind 'Files' detected"

### ISSUE THREAD

**Issue by erf** [elysiajs/elysia#547] opened 2024-03-17 20:21 UTC
### What version of Elysia.JS is running?

is `Elysia` a cli tool ? updating from 0.8.1 -> 1.0.0

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

I found the issue to be the following:
```
import { Elysia } from 'Elysia'
```
is working fine in `0.8.1` .. but causing a crash in `1.0.0`

I changed this to:
```
import { Elysia } from 'elysia'
```

and it is working fine again 

### What is the expected behavior?

used to work fine before

### What do you see instead?

Error message when importing using `Elysia`:

```
 % bun run src/index.js
1 | /** The base Error type thrown for all TypeBox exceptions  */
2 | export class TypeBoxError extends Error {
3 |     constructor(message) {
4 |         super(message);
            ^
error: Duplicate type kind 'Files' detected
      at new TypeBoxError (/myproject/node_modules/@sinclair/typebox/build/import/type/error/error.mjs:4:9)
      at new TypeSystemDuplicateTypeKind (/myproject/node_modules/@sinclair/typebox/build/import/system/system.mjs:10:9)
      at Type (/myproject/node_modules/@sinclair/typebox/build/import/system/system.mjs:27:19)
      at /myproject/node_modules/elysia/dist/bun/index.js:4720:13
```

### Additional information

Could perhaps mention this in the release notes?

**Comment by SaltyAom** [comment] 2024-03-18 06:26
Have you try removing `node_modules` and `bun.lockb` and try again yet?

**Comment by mehtaabGill** [comment] 2024-04-01 05:13
also facing this issue but im importing from `elysia` (lowercase)

**Comment by qlaffont** [comment] 2024-04-02 07:08
same for me since I have can be reproducible here : https://github.com/qlaffont/starter-elysia

**Comment by qlaffont** [comment] 2024-04-02 12:45
I have found the issue, multiple elysia are imported (check your librairies and verify that elysia is not exported on one of your imported librairies)

**Comment by SaltyAom** [comment] 2024-08-30 20:21
Should have been fixed by the latest version as conditional check for format, see fbadb73

Closing as completed. If the problem still persist, feel free to reopen the issue. Thanks.

**Closed by SaltyAom** 2024-08-30 20:21 UTC
Labels: bug
