### ISSUE TITLE
Context in derive() is missing

### ISSUE THREAD

**Issue by ycytt-rs** [elysiajs/elysia#568] opened 2024-03-25 13:22 UTC
### What version of Elysia.JS is running?

1.0.8

### What platform is your computer?

Linux x86

### What steps can reproduce the bug?

src/index.ts: 
```typescript
import { Elysia } from "elysia";

import mid from './mid';

const app = new Elysia()
  .derive(mid())
  .get("/", () => "Hello Elysia").listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```
src/mid.ts
```typescript
import { Context } from "elysia";

const mid = () => {
  return ({ cookie, headers }: Context) => {
    console.log('-------------- mid ----------------');
    console.log('request');
    console.log('headers');
    console.dir(headers);
    console.log('cookie');
    console.dir(cookie);

    console.log('------------------------------');

    return {
      testing: {
        msg: 's',
      },
    };
  };
};

export default mid;
```
.env.build:
```console
NODE_ENV=production
```

build: 
```console
bun build --env-file=.env.build ./src/index.ts --outfile testing.app --compile --minify --sourcemap
```

running:
```sh
./testing.app
```

### What is the expected behavior?
```sh
-------------- mid ----------------
request
headers
{
  host: "localhost:3000",
  connection: "keep-alive",
  "cache-control": "max-age=0",
  "upgrade-insecure-requests": "1",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "sec-fetch-mode": "navigate",
  "sec-fetch-dest": "document",
  "accept-encoding": "gzip, deflate, br, zstd",
  "accept-language": "en-US,en;q=0.9",
  cookie: "_sid=sess_lu6y8pyw000asy877vgpsgo2; _cid=cln_lu6y8pyw000bsy87gchm3szd",
  "sec-ch-ua": "\"Chromium\";v=\"123\", \"Not:A-Brand\";v=\"8\"",
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": "\"Linux\"",
  "sec-fetch-site": "none",
  "sec-fetch-user": "?1",
}
cookie
{
  _sid: {
    value: "sess_lu6y8pyw000asy877vgpsgo2",
  },
  _cid: {
    value: "cln_lu6y8pyw000bsy87gchm3szd",
  },
}
------------------------------
```
### What do you see instead?
```sh
-------------- mid ----------------
request
headers
{
  host: "localhost:3000",
  connection: "keep-alive",
  "cache-control": "max-age=0",
  "upgrade-insecure-requests": "1",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "sec-fetch-mode": "navigate",
  "sec-fetch-dest": "document",
  "accept-encoding": "gzip, deflate, br, zstd",
  "accept-language": "en-US,en;q=0.9",
  cookie: "_sid=sess_lu6y8pyw000asy877vgpsgo2; _cid=cln_lu6y8pyw000bsy87gchm3szd",
  "sec-ch-ua": "\"Chromium\";v=\"123\", \"Not:A-Brand\";v=\"8\"",
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": "\"Linux\"",
  "sec-fetch-site": "none",
  "sec-fetch-user": "?1",
}
cookie
undefined
------------------------------
```

**Comment by ycytt-rs** [comment] 2024-03-25 13:35
I guess it is related to `--minify` flag. `minify` would make the code not recognizable by `Sucrose`.

Also, tuning `aot` in Elysia to false can also solve this issue.

**Comment by SaltyAom** [comment] 2024-08-30 20:03
Should have been fixed with previous subsequent version of Elysia, as unable to reproduce on the latest (1.1.9)

**Closed by SaltyAom** 2024-08-30 20:03 UTC
Labels: bug
