### ISSUE TITLE
Elysia main class has any type

### ISSUE THREAD

**Issue by lucca-poli** [elysiajs/elysia#217] opened 2023-09-22 19:49 UTC
When I hover "Elysia" class, it has the following data
```
(alias) class Elysia
(alias) const Elysia: typeof Elysia
import Elysia
───────────────────────────────────────────────
### Elysia Server
Main instance to create web server using Elysia
───────────────────────────────────────────────
*@example*  
import { Elysia } from 'elysia'

new Elysia()
    .get("/", () => "Hello")
    .listen(8080)
```
but my app variable has type "any", and all the other methods like "use" and "listen" have type "any" and are not suggested.
Is this normal?

Here's my current code in index.ts:
```
import { Elysia } from "elysia";
import { html } from "@elysiajs/html";

const app = new Elysia()
    .use(html())
    .listen(8080);

console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`);
```
and tsconfig.json:
```
{
  "compilerOptions": {
<...some-options...>
    "types": [
      "bun-types"
    ]
  }
}
```

**Comment by SaltyAom** [comment] 2023-09-26 11:52
Have you set `strict: true` in `tsconfig.json`?

**Comment by Sergeant61** [comment] 2023-09-26 18:43
Hi same problem. I didn't have such a problem on my Mac computer. I started experiencing this on the Win 11 subsystem.

Error: Property 'state' does not exist on type 'Elysia<"", { request: {}; store: {}; }, { type: {}; error: {}; }, {}, {}, false>'.ts(2339)

![image](https://github.com/elysiajs/elysia/assets/25281038/736cfdd9-2ef3-4ce5-a125-511fbbdf9f47)


tsconfig.json
```js
{
  "compilerOptions": {
    "target": "ESNext",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node",
    "types": ["bun-types"],
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitAny": true,
    "strictFunctionTypes": true,  
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  }
}
```

setup.ts
```js

import Elysia from 'elysia'
import { User } from './database/models/users'

const setup = new Elysia({
  name: 'setup',
})
  .state('User', User)
  .decorate('ApiResponse', (data: any) => {
    return new Response(JSON.stringify(data))
  })

export default setup
```

**Comment by SaltyAom** [comment] 2024-08-30 11:07
Closing as unable to reproduce, feels free to reopen a new issue if this problem still occurs.

Thanks.

**Closed by SaltyAom** 2024-08-30 11:07 UTC
