### ISSUE TITLE
onError is called without error and code when using aot = false

### ISSUE THREAD

**Issue by Richtervn** [elysiajs/elysia#293] opened 2023-11-04 17:04 UTC
```Typescript
const app = new Elysia({ aot: false })
  .onError((c) => {
    console.log(c.error, c.code);
    return 'dummy';
  });

app.get("/", () => {
  throw new Error("test");
});
```
  
With `aot: true`, the error and the code is printed without any problem.  
But with `aot: false`, both is `undefined`.

**Comment by SaltyAom** [comment] 2024-08-30 16:31
Should have been fixed by previous subsequent patches at some point.

Unable to reproduce with the following code:
```ts
const app = new Elysia({ aot: false })
	.onError((c) => {
		console.log(c.error)
		return 'dummy'
	})
	.get('/', () => {
		throw new Error('test')
	})

app.handle(new Request('http://localhost'))
	.then((x) => x.text())
	.then(console.log)
```

Closing as complete.

**Closed by SaltyAom** 2024-08-30 16:31 UTC
