### ISSUE TITLE
Crush on wrong request

### ISSUE THREAD

**Issue by alhimikix** [elysiajs/elysia#120] opened 2023-09-11 10:14 UTC
system: Mac OS Sonoma 14

Request

POST http://localhost:3000/test
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files1"; filename="img.png"
Content-Type: image/png

< ./img.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="img.png"
Content-Type: image/png

< ./img.png

result 

> bun run --watch src/index.ts

🦊 Elysia is running at localhost:3000

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

or

zsh: segmentation fault  bun run --watch src/index.ts

Code: 

import { Elysia, t } from "elysia";
import { swagger } from '@elysiajs/swagger'

const app = new Elysia()
    .use(swagger())
    .get("/", () => "Hello Elysia")
    .post('/test', async ({body: {text}}) => {
        return text
    }, {
        body: t.Object({
            text: t.String()
        })
    })
    .listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);

**Comment by SaltyAom** [comment] 2023-11-16 11:11
Can't reproduce on latest Bun and Elysia version.

Closing, feels free to reopen the issue if the problem still persists.

**Closed by SaltyAom** 2023-11-16 11:11 UTC
