### ISSUE TITLE
Optional params not work

### ISSUE THREAD

**Issue by Farnsi** [elysiajs/elysia#435] opened 2024-01-22 16:42 UTC
View closed https://github.com/elysiajs/elysia/issues/68
exactly the same problem

elysia: 0.8.9
@elysiajs/eden: 0.8.1

**Comment by floydjones1** [comment] 2024-01-22 16:56
Probably caused this to regress too?
https://github.com/elysiajs/elysia/issues/436

**Comment by SupertigerDev** [comment] 2024-04-28 19:49
fr.

**Comment by JustMrMendez** [comment] 2024-07-09 18:26
Same problem here, `t.Optional()` and I'm getting a validation error.

**Comment by SaltyAom** [comment] 2024-08-30 18:21
Unable to reproduce in the latest version (1.1.9) with the following code:
```ts
const app = new Elysia().get('/qtest', ({ query }) => query, {
	query: t.Object({
		pageNum: t.Optional(t.Numeric({ default: 1 })),
		pageSize: t.Optional(t.Numeric({ default: 10 }))
	})
})

app.handle(new Request('http://localhost/qtest'))
	.then((x) => x.json())
	.then(console.log)
```

Probably have been fixed by 1.0 and 1.1, if the problem still persists feel free to reopen the issue.

**Closed by SaltyAom** 2024-08-30 18:21 UTC

**Comment by SupertigerDev** [comment] 2024-08-30 19:05
> Unable to reproduce in the latest version (1.1.9) with the following code:
> ```ts
> const app = new Elysia().get('/qtest', ({ query }) => query, {
> 	query: t.Object({
> 		pageNum: t.Optional(t.Numeric({ default: 1 })),
> 		pageSize: t.Optional(t.Numeric({ default: 10 }))
> 	})
> })
> 
> app.handle(new Request('http://localhost/qtest'))
> 	.then((x) => x.json())
> 	.then(console.log)
> ```
> 
> Probably have been fixed by 1.0 and 1.1, if the problem still persists feel free to reopen the issue.

Those are not params... Those are query.

**Comment by SaltyAom** [comment] 2024-09-04 05:27
From SupertigerDev, closed as complete.

> ohh my bad, seems like its working now. sorry, thanks!

https://github.com/elysiajs/elysia/issues/805#issuecomment-2327150666

**Comment by jasperdunn** [comment] 2024-09-06 03:36
![Screenshot 2024-09-06 at 1 34 56 PM](https://github.com/user-attachments/assets/a80347d1-376a-4ae3-9273-1f428a10109e)

`elysia: 1.1.12`
This is happening to me too, I'm expecting query to be of type:

```ts
{
  pageNum: number;
  pageSize: number;
}
```

**Comment by kravetsone** [comment] 2024-09-06 05:39
> ![Screenshot 2024-09-06 at 1 34 56 PM](https://github.com/user-attachments/assets/a80347d1-376a-4ae3-9273-1f428a10109e)
> 
> `elysia: 1.1.12`
> This is happening to me too, I'm expecting query to be of type:
> 
> ```ts
> {
>   pageNum: number;
>   pageSize: number;
> }
> ```

Wtf
You mark it as optional and expect it to be required?

**Comment by jasperdunn** [comment] 2024-09-06 06:21
> Wtf You mark it as optional and expect it to be required?

Sorry if I haven't explained it clearly. This is what I want:

It's optional, if I don't provide a value then it should use the default value. If this is not at all what defaultValue is for, then please help me understand.

Thanks

**Comment by kravetsone** [comment] 2024-09-06 08:08
> > Wtf You mark it as optional and expect it to be required?
> 
> Sorry if I haven't explained it clearly. This is what I want:
> 
> It's optional, if I don't provide a value then it should use the default value. If this is not at all what `default` is for, then please help me understand.
> 
> The client `query` object should have `number | undefined` properties sure, but the server itself should know that the values exist at the `beforeHandle` shouldn't it? Or does the default get applied after validation? 🤔 
> 
> Thanks

Ahh sorry i misunderstood 

Can you check it with plain typebox?
With `Static`

**Comment by jasperdunn** [comment] 2024-09-08 01:12
> Can you check it with plain typebox? With `Static`
Reading through again I think my issue is different to the original, I'll write up a separate issue.
I'll try and explain it better there, thanks.
