### ISSUE TITLE
WebSocket endpoints don't work if they are "used"

### ISSUE THREAD

**Issue by mrctrifork** [elysiajs/elysia#553] opened 2024-03-18 15:08 UTC
### What version of Elysia.JS is running?

1.0.8

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

Use this client:

```js
// bun run client.ts

const ws = new WebSocket('ws://localhost:4000/stuff')
ws.onopen = () => {
  console.log('Opened')
}
ws.onclose = () => {
  console.log('Closed')
}
ws.onmessage = ev => console.log('onmessage', (ev.data))
```

With the following server, the websocket connection is stablished and "Opened" is logged to the console:

```typescript
import { Elysia } from 'elysia'

const app = new Elysia()

app
.group('/stuff', app => app
.ws('/', {
  message(ws, message) {
     ws.send(message)
  }
}))
.listen(4000, () => console.log('ready'))
```

The following server doesn't work; client directly states "Closed"

```typescript
import { Elysia } from 'elysia'

const stuff = new Elysia()
.group('/stuff', app => app
.ws('/', {
  message(ws, message) {
     ws.send(message)
  }
}))

new Elysia()
  .use(stuff)
  .listen(4000, () => console.log('ready'))
```

### What is the expected behavior?

Both clients should state "Opened".

### What do you see instead?

One client directly does not establish the websocket connection

**Comment by mrctrifork** [comment] 2024-03-18 15:29
After [digging into the discord for more information I've found an approach that works](https://discord.com/channels/1044804142461362206/1187220358735089714) (see last comment) although I would argue this is still a bug or the documentation doesn't make a mention of what's the actual difference between `.group` and `new Elysia( { prefix: '...' })`


Using the latter example seems to work:


```
const stuff = new Elysia({ prefix: '/stuff'})
.ws('/', {
  message(ws, message) {
     ws.send(message)
  }
})

const steff = new Elysia({ prefix: '/steff'})
.ws('/', {
  message(ws, message) {
     ws.send(message)
  }
})
new Elysia()
  .use(stuff)
  .use(steff)
  .listen(4000, () => console.log('ready'))
```

**Comment by SaltyAom** [comment] 2024-08-30 20:24
Should have probably been fixed by previous subsequent version of Elysia, as unable to reproduce with latest version (1.1.9) with the following code:
```ts
new Elysia().group('/stuff', (app) =>
	app.ws('/', {
		message(ws, message) {
			ws.send(message)
		}
	})
)

new Elysia().use(stuff).listen(4000, () => console.log('ready'))
{
	const ws = new WebSocket('ws://localhost:4000/stuff')
	ws.onopen = () => {
		console.log('Opened')
	}
	ws.onclose = () => {
		console.log('Closed')
	}
	ws.onmessage = (ev) => console.log('onmessage', ev.data)
}

await Bun.sleep(1000)

{
	const ws = new WebSocket('ws://localhost:4000/stuff')
	ws.onopen = () => {
		console.log('Opened')
	}
	ws.onclose = () => {
		console.log('Closed')
	}
	ws.onmessage = (ev) => console.log('onmessage', ev.data)
}
```

If the problem still persist, feel free to reopen the issue.

**Closed by SaltyAom** 2024-08-30 20:24 UTC
Labels: bug
