### ISSUE TITLE
EINVAL: MacOS does not support sending non-regular files

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [elysiajs/elysia#327] opened 2023-11-22 11:02 UTC
Hey there, triing to use elysia with remix.run. 

Using the static plugin i get the following error
```

EINVAL: MacOS does not support sending non-regular files
   path: "/***/***/***/***/***/workspaces/website/public/"
 syscall: "sendfile"
   errno: -22
```

**Comment by mvolkmann** [comment] 2023-12-26 17:12
I believe this happens because Elysia does not serve the "index.html" file by default. Trying adding "/index.html" to the end of the URL.

This feels like a bug to me. I think Elysia should default to servering that file when no file is specified.

**Comment by broisnischal** [comment] 2024-06-26 16:59
```

**Comment by SaltyAom** [comment] 2024-08-30 11:22
I recall that the issue has been reported to Bun and is now fixed several months ago, the problem is I'm not sure which one and I'm unable to replicate the issue on my end.

Closing as fixed.

**Closed by SaltyAom** 2024-08-30 11:22 UTC
