### ISSUE TITLE
TObject from createInsertSchema not compatible with Elysia TObject

### ISSUE THREAD

**Issue by primadi** [elysiajs/elysia#303] opened 2023-11-11 15:18 UTC
```js
import { pgTable, text } from "drizzle-orm/pg-core"
import { createInsertSchema } from "drizzle-typebox"
import { t } from "elysia"

const user = t.Object({ id: t.String(), name: t.String() })
const omitid_from_user = t.Omit(user, ["id"]) // This Line is OK in TypeScript

//////////////////////////////

const userTable = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name"),
})

const user2 = createInsertSchema(userTable)
const omitid_from_user2 = t.Omit(user2, ["id"]) // This Line is error in TypeScript
```
Elysia version: 0.7.24
drizzle-typebox version: 0.1.1

Error in TypeScript :

```
 No overload matches this call.
  The last overload gave the following error.
    Argument of type 'TObject<{ id: TString; name: TOptional<TNullable<TString>>; }>' is not assignable to parameter of type 'TSchema'.
      Property '[Kind]' is missing in type 'TObject<{ id: TString; name: TOptional<TNullable<TString>>; }>' but required in type 'TSchema'.ts(2769)
typebox.d.ts(66, 5): '[Kind]' is declared here.
typebox.d.ts(861, 5): The last overload is declared here.
```
How to reproduce : just copy-paste above code into vscode, Typescript Error is : Property '[Kind]' is missing in type 'TObject<{ id: TString; name: TOptional<TNullable<TString>>; }>' but required in type 'TSchema'.ts(2769)

Thanks.

**Comment by vacuumdreams** [comment] 2024-04-01 10:38
@primadi I was having the same issue a few weeks ago, but it seems like in the recent v1+ release it works perfectly fine.

**Comment by SaltyAom** [comment] 2024-08-30 17:06
This problem is caused by mismatched TypeBox version.

Should have been fixed by specifying TypeBox version in override field in package.json as follows:
```ts
{
    "override": {
        "@sinclair/typebox": "0.32.4"
    }
}
```

Closing as complete

**Closed by SaltyAom** 2024-08-30 17:06 UTC
