### ISSUE TITLE
SyntaxError: Unexpected end of JSON input with method ALL

### ISSUE THREAD

**Issue by nacimgoura** [elysiajs/elysia#349] opened 2023-12-07 09:33 UTC
Hello,
when i use `.all("/*", async ({ request, set, body }) =>` I have the error `SyntaxError: Unexpected end of JSON input`
If i remove `body` param, I don't have any error.
But `body` is necessary to match with some method like POST.

With the last version of elysia I have the message `fetch() request with GET/HEAD/OPTIONS method cannot have body.`

**Comment by SaltyAom** [comment] 2024-08-30 18:10
This probably has been fixed in previous subsequent patches of Elysia mostly in both 1.0 and 1.1 as unable to reproduce in the latest version (1.1.9) with the following code:
```ts
const app = new Elysia()
	.all('/*', async ({ request, set, body }) => 'ok')
	.listen(3000)

app.handle(new Request('http://localhost:3000'))
	.then((x) => x.text())
	.then(console.log)

app.handle(
	new Request('http://localhost:3000', {
		method: 'POST',
		headers: {
			'content-type': 'text/plain'
		},
		body: 'hello world'
	})
)
	.then((x) => x.text())
	.then(console.log)
```

If the problem still exists, feel free to reopen the issue.

**Closed by SaltyAom** 2024-08-30 18:10 UTC
