### ISSUE TITLE
context of handler.parse is underpopulated

### ISSUE THREAD

**Issue by DarkMio** [elysiajs/elysia#407] opened 2024-01-10 13:39 UTC
I've noticed that almost all fields are not populated when handling an incoming quest via `parse`:

```ts
new Elysia().post("/", async () => {}, {
    parse: async ctx => {
        const contentType = ctx.headers["content-type"];
        // and so on
    },
});
```
Which causes:
```ts
[10-01-2024 12:48:37] [!Default:warn] Error: undefined is not an object (evaluating 'ctx.headers["content-type"]')
Stack: 
 TypeError: undefined is not an object (evaluating 'ctx.headers["content-type"]')
    at <anonymous> (/opt/stuff/src/api/index.ts:96:45)
    at parse (/opt/stuff/src/api/index.ts:26:23)
    at <anonymous> (:53:19)
    at <anonymous> (:44:25)
    at map (:220:25)
```
Seemingly population can be triggered by serializing the context, such as:
```ts
new Elysia().post("/", async ({ ... }) => { /* ... */ }, {
    parse: async ctx => {
        JSON.stringify(ctx.headers);
        // this now passes fine
        const contentType = ctx.headers["content-type"];
        // and so on
    },
});
```
On random note, doing a `JSON.stringify(ctx.headers)` in a breakpoint-halted debugging session does not make `ctx.headers` show up. 

If this is intended, then the type is wrong: `BodyHandler<TypedRoute, Decorators>`

- Bun Version: `1.0.21`
- minimum affected Elysia versions: `0.7.15` - `0.8.8`

**Comment by bogeychan** [comment] 2024-01-28 04:26
Use the second argument to get the `Content-Type` inside `parse` instead of `ctx.headers["content-type"]`:

```ts
parse(ctx, contentType) {

}
```

---

@SaltyAom, the problem is that `hasHeaders` is `false` for `parse`:

https://github.com/elysiajs/elysia/blob/742707961ce125139c9f287fd3147ec1fd7c8a41/src/compose.ts#L590-L593

A quick solution is to add `...hooks.parse` to the `lifeCycleLiteral`:

https://github.com/elysiajs/elysia/blob/742707961ce125139c9f287fd3147ec1fd7c8a41/src/compose.ts#L570-L579

Either something like that or remove `headers` from the handler's type and only allow access to `ctx.body`, `ctx.request`? But what about `derive` / `store`-methods?

**Comment by SaltyAom** [comment] 2024-08-30 19:21
Should have been fixed by previous subsequent version of Elysia also problem mentioned by Bogeychan has been fixed.

Also I'm unable to reproduce the problem on my end with the following code:
```ts
const app = new Elysia().post('/', async () => 'ok', {
	parse: async (ctx) => {
		const contentType = ctx.headers['content-type']
	}
})

app.handle(
	new Request('http://localhost', {
		method: 'POST',
		headers: {
			'content-type': 'application/json'
		},
		body: JSON.stringify({ name: 'Elysia' })
	})
)
	.then((x) => x.text())
	.then(console.log)
```

So I assume that the problem has been fixed. If the problem still persists on your end, feel free to reopen the issue. Thanks.

**Closed by SaltyAom** 2024-08-30 19:21 UTC
