### ISSUE TITLE
Docker oven/bun port in use even when it's not

### ISSUE THREAD

**Issue by gluax** [elysiajs/elysia#80] opened 2023-08-01 07:34 UTC
When using the official bun docker container, `oven/bun` elysia` always reports that the port is in use. Even when it's not. Using Bun's built-in `Bun.serve` on the same port will function just fine.

Bun version: `0.7.1`
elysia: "latest"

**Comment by SaltyAom** [comment] 2023-11-16 08:52
Can you provide a minimal reproducible example for this? thanks.

**Comment by SaltyAom** [comment] 2024-08-30 10:39
Closing as unable to reproduce and depends on Bun not Elysia.

Feels free to reopen issue on http://github.com/oven-sh/bun/issues.

Thanks.

**Closed by SaltyAom** 2024-08-30 10:39 UTC

**Comment by peterferguson** [comment] 2024-10-01 09:46
Hey I am getting this error too, it seems to happen when you have a `PORT` env var set [as suggested here](https://elysiajs.com/patterns/deployment.html#railway)

repro: https://github.com/peterferguson/elysia-port-bug

There are two commits the first breaks the server.

The second stops the crash by removing `listen`
