### ISSUE TITLE
async derive does not get awaited

### ISSUE THREAD

**Issue by lithdew** [elysiajs/elysia#588] opened 2024-04-02 11:58 UTC
### What version of Elysia.JS is running?

1.0.11

### What platform is your computer?

Darwin 23.4.0 arm64 arm

### What steps can reproduce the bug?

```ts
export async function deriveSession({ cookie }: Context<any>) {
  return { session: "123" };
}
```

Use the `derive()` above as `.derive(deriveSession)`. The field `session` is undefined in all handlers.

**Comment by SaltyAom** [comment] 2024-04-26 18:00
Should have been fixed in 1.0.14.

**Comment by SaltyAom** [comment] 2024-08-30 20:39
Closing as complete, as unable to reproduce on the latest version of Elysia and lack of interaction.

Feels free to reopen the issue if the problem still persist.

**Closed by SaltyAom** 2024-08-30 20:39 UTC
Labels: bug
