### ISSUE TITLE
Websocket type inference not on parity with normal routes

### ISSUE THREAD

**Issue by ricin9** [elysiajs/elysia#248] opened 2023-10-02 22:26 UTC
Hello, when using plugins like the official bearer plugin, you can access bearer object in request context in http routes and it is type-safe and all, but not when you use websockets even though the object is actually there, simple demonstration :

```ts
export const app = new Elysia()
    .derive((app) => ({ someKey: "someValue" }))
    .get("/", (ctx) => {
        console.log(ctx.someKey, typeof ctx.someKey); // Output : someValue string
    })
    .ws("/ws", {
        open(ws) {
            console.log(ws.data.someKey, typeof ws.data.someKey); // Output : someValue string, but IDE complains
        },
    })
    .listen(3000);
```
IDE complains that property someKey doesn't exist in _ws.data_  even though it exists
`
Property 'someKey' does not exist on type '{ body: unknown; query: Record<string, string | null>; params: never; headers: Record<string, string | null>; cookie: Record<string, Cookie<any>>; set: { ...; }; path: string; request: Request; store: {}; }'.
`
JSON.stringify(ws.data, null, 2) output : 
```json
{
  "request": {},
  "store": {},
  "qi": -1,
  "path": "/ws",
  "set": {
    "headers": {},
    "status": 200
  },
  "headers": {
    "host": "localhost:3000",
    "connection": "Upgrade",
    "upgrade": "websocket",
    "sec-websocket-version": "13",
    "sec-websocket-key": "uhTheQDaIsRhC2tY4TlBhg=="
  },
  "cookie": {},
  "query": {},
  "someKey": "someValue"
}
```

My environment :
Bun : v1.0.3
Elysia : 0.7.15

**Comment by SaltyAom** [comment] 2023-11-16 12:13
Doesn't seem to happen on the latest version (0.7.26).

<img width="1920" alt="Screenshot 2566-11-16 at 19 12 27" src="https://github.com/elysiajs/elysia/assets/35027979/07d4d8b0-e663-40f8-9bbf-7a6252dd5054">

Closing as assuming that the issue is fixed in some version.

Feels free to reopen if the issue stills persists

**Closed by SaltyAom** 2023-11-16 12:13 UTC

**Comment by ricin9** [comment] 2023-11-16 20:22
can confirm it's working, good work thank you :+1:
